//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.28 at 03:30:59 PM MST 
//


package org.icefaces.application.showcase.view.jaxb;

import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}content-descriptor" maxOccurs="unbounded"/>
 *         &lt;element ref="{}content-resources"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contentDescriptor",
    "contentResources"
})
@XmlRootElement(name = "content")
public class Content implements Serializable {

    @XmlElement(name = "content-descriptor", required = true)
    protected List<ContentDescriptor> contentDescriptor;
    @XmlElement(name = "content-resources", required = true)
    protected ContentResources contentResources;

    /**
     * Gets the value of the contentDescriptor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contentDescriptor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContentDescriptor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContentDescriptor }
     * 
     * 
     */
    public List<ContentDescriptor> getContentDescriptor() {
        if (contentDescriptor == null) {
            contentDescriptor = new ArrayList<ContentDescriptor>();
        }
        return this.contentDescriptor;
    }

    /**
     * Gets the value of the contentResources property.
     * 
     * @return
     *     possible object is
     *     {@link ContentResources }
     *     
     */
    public ContentResources getContentResources() {
        return contentResources;
    }

    /**
     * Sets the value of the contentResources property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentResources }
     *     
     */
    public void setContentResources(ContentResources value) {
        this.contentResources = value;
    }

}
