//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.28 at 03:30:59 PM MST 
//


package org.icefaces.application.showcase.view.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}documents" minOccurs="0"/>
 *         &lt;element ref="{}tlds" minOccurs="0"/>
 *         &lt;element ref="{}tutorials" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="templateRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documents",
    "tlds",
    "tutorials"
})
@XmlRootElement(name = "documentation")
public class Documentation implements Serializable {

    protected Documents documents;
    protected Tlds tlds;
    protected Tutorials tutorials;
    @XmlAttribute
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected ResourceType templateRef;

    /**
     * Gets the value of the documents property.
     * 
     * @return
     *     possible object is
     *     {@link Documents }
     *     
     */
    public Documents getDocuments() {
        return documents;
    }

    /**
     * Sets the value of the documents property.
     * 
     * @param value
     *     allowed object is
     *     {@link Documents }
     *     
     */
    public void setDocuments(Documents value) {
        this.documents = value;
    }

    /**
     * Gets the value of the tlds property.
     * 
     * @return
     *     possible object is
     *     {@link Tlds }
     *     
     */
    public Tlds getTlds() {
        return tlds;
    }

    /**
     * Sets the value of the tlds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tlds }
     *     
     */
    public void setTlds(Tlds value) {
        this.tlds = value;
    }

    /**
     * Gets the value of the tutorials property.
     * 
     * @return
     *     possible object is
     *     {@link Tutorials }
     *     
     */
    public Tutorials getTutorials() {
        return tutorials;
    }

    /**
     * Sets the value of the tutorials property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tutorials }
     *     
     */
    public void setTutorials(Tutorials value) {
        this.tutorials = value;
    }

    /**
     * Gets the value of the templateRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public ResourceType getTemplateRef() {
        return templateRef;
    }

    /**
     * Sets the value of the templateRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTemplateRef(ResourceType value) {
        this.templateRef = value;
    }

}
