//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.28 at 03:30:59 PM MST 
//


package org.icefaces.application.showcase.view.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import java.io.Serializable;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.icefaces.application.showcase.view.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory implements Serializable {

    private final static QName _Resource_QNAME = new QName("", "resource");
    private final static QName _ResourceReference_QNAME = new QName("", "resource-reference");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.icefaces.application.showcase.view.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ContentResources }
     * 
     */
    public ContentResources createContentResources() {
        return new ContentResources();
    }

    /**
     * Create an instance of {@link JspxPages }
     * 
     */
    public JspxPages createJspxPages() {
        return new JspxPages();
    }

    /**
     * Create an instance of {@link NavigationDefault }
     * 
     */
    public NavigationDefault createNavigationDefault() {
        return new NavigationDefault();
    }

    /**
     * Create an instance of {@link Example }
     * 
     */
    public Example createExample() {
        return new Example();
    }

    /**
     * Create an instance of {@link ContentDescriptor }
     * 
     */
    public ContentDescriptor createContentDescriptor() {
        return new ContentDescriptor();
    }

    /**
     * Create an instance of {@link SourceCode }
     * 
     */
    public SourceCode createSourceCode() {
        return new SourceCode();
    }

    /**
     * Create an instance of {@link Navigation }
     * 
     */
    public Navigation createNavigation() {
        return new Navigation();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link Documents }
     * 
     */
    public Documents createDocuments() {
        return new Documents();
    }

    /**
     * Create an instance of {@link ResourceType }
     * 
     */
    public ResourceType createResourceType() {
        return new ResourceType();
    }

    /**
     * Create an instance of {@link Tutorials }
     * 
     */
    public Tutorials createTutorials() {
        return new Tutorials();
    }

    /**
     * Create an instance of {@link Application }
     * 
     */
    public Application createApplication() {
        return new Application();
    }

    /**
     * Create an instance of {@link Beans }
     * 
     */
    public Beans createBeans() {
        return new Beans();
    }

    /**
     * Create an instance of {@link Node }
     * 
     */
    public Node createNode() {
        return new Node();
    }

    /**
     * Create an instance of {@link Documentation }
     * 
     */
    public Documentation createDocumentation() {
        return new Documentation();
    }

    /**
     * Create an instance of {@link Tlds }
     * 
     */
    public Tlds createTlds() {
        return new Tlds();
    }

    /**
     * Create an instance of {@link Content }
     * 
     */
    public Content createContent() {
        return new Content();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "resource")
    public JAXBElement<ResourceType> createResource(ResourceType value) {
        return new JAXBElement<ResourceType>(_Resource_QNAME, ResourceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "resource-reference")
    public JAXBElement<ReferenceType> createResourceReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_ResourceReference_QNAME, ReferenceType.class, null, value);
    }

}
